### ISSUE TITLE
Feature Request Thread

### ISSUE THREAD

**Issue by molarmanful** [vihanb/PPCG-Design#10]
This is the place to ask for features to incorporate into the userscript. Please do not close until we get our official design!

**Comment by molarmanful** [comment]
Me first: We could add colors for specific languages, depending on the name. (This could be done with an algorithm, or we hand-pick the colors and code them in.) Example: Javascript could be a gold-yellow color.

**Comment by vihanb** [comment]
An increased Leaderboard quota. This will prevent quota limits from disabling the leaderboard. This can be done by creating a StackApps post.

**Comment by addisoncrump** [comment]
The leaderboard should also show the username of the person who posted the answer's.

**Comment by addisoncrump** [comment]
The hexagonal pattern on the header of the main page should go down to the bottom of the page like in meta.

**Comment by molarmanful** [comment]
@VTCAKAVSMoACE That's what I thought, but apparently there was too much green or something. (It doesn't look too good in my opinion, though.)

**Comment by addisoncrump** [comment]
@molarmanful Yeah, no, it's definitely necessary - it doesn't make sense to switch styles, and it feels empty without the full page being patterned.

**Comment by molarmanful** [comment]
@VTCAKAVSMoACE That's what I've been thinking. https://github.com/vihanb/PPCG-Design/issues/15

**Comment by addisoncrump** [comment]
Also, make the userscript download and run the _latest_ script, that way, we can always be updated.

**Comment by ETHproductions** [comment]
@VTCAKAVSMoACE Done. I believe it will only auto-update when we update the version number, though.

**Comment by vihanb** [comment]
@VTCAKAVSMoACE The leaderboard now shows the user with a link to their profile

**Comment by ETHproductions** [comment]
I lllllllllllllike it! The leaderboard works pretty much perfectly for me now.

**Comment by addisoncrump** [comment]
For answers with langs that exist in tryitonline, have the output from those codes go under the first code block in the answer. There's a copy of something that does this on [this git repo](https://github.com/Mego/DataBot/blob/master/databot.js) already.

**Comment by vihanb** [comment]
Interesting idea but how would the program's input be received? Should it look for a [tryitonline] link?

**Comment by vihanb** [comment]
Nvm, CORS makes it impossible

**Comment by addisoncrump** [comment]
Yeah - exactly how it would work. So, maybe instead of under the code block, under the tryitonline link.

**Comment by addisoncrump** [comment]
CORS?

**Comment by ETHproductions** [comment]
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by vihanb** [comment]
cross-origin-resource-sharing. I can only AJAX a page from the same domain

**Comment by ETHproductions** [comment]
How does the chat-bot do it then?

**Comment by vihanb** [comment]
what chat-bot?

**Comment by addisoncrump** [comment]
The chat bot does it just fine from c9.io.

**Comment by addisoncrump** [comment]
https://github.com/Mego/DataBot/blob/master/databot.js

**Comment by vihanb** [comment]
What's c9.io

**Comment by addisoncrump** [comment]
https://ide.c9.io/vtcakavsmoace/databot-js

**Comment by vihanb** [comment]
must not be running in browser then

**Comment by addisoncrump** [comment]
It isn't, but does that matter?

**Comment by vihanb** [comment]
node.js isn't client-side so cors isn't an issue

**Comment by vihanb** [comment]
Actually a proxy could be used

**Comment by addisoncrump** [comment]
Replace this text with something actually relevant to our site:

![screen shot 2016-01-30 at 4 37 49 pm](https://cloud.githubusercontent.com/assets/10711159/12696989/e1a05a5a-c76f-11e5-851c-5dce7f4269c6.png)

**Comment by JJ-Atkinson** [comment]
Add a question of the day panel. #30

**Comment by addisoncrump** [comment]
Customize Chat in similar fashion to ppcg.alt.user.js.

**Comment by vihanb** [comment]
Hmm I _guess_ that's possible.

**Comment by vihanb** [comment]
Meta posts could be shown on main with perhaps a different color to distinguish them

**Comment by vihanb** [comment]
For [code-golf] questions a "Current Winner" could be shown

**Comment by RikerW** [comment]
I like that idea.

**Comment by RikerW** [comment]
Where to put it?  Like directly above the current toggly leaderboard thing, at the top of the post, etc?

**Comment by vihanb** [comment]
I was thinking of a banner  around here:

<img width="762" alt="screen shot 2016-02-06 at 8 43 58 am" src="https://cloud.githubusercontent.com/assets/15314511/12867868/ebf91648-ccad-11e5-8b39-720adc6db191.png">

**Comment by addisoncrump** [comment]
That sounds pretty cool.

**Comment by RikerW** [comment]
Okay, that might work.

**Comment by addisoncrump** [comment]
Can I be added as a Safari Guinea Pig contributor? :P Even though I can't do JS, I point out way too many issues.

**Comment by vihanb** [comment]
@VTCAKAVSMoACE sure, added you

**Comment by addisoncrump** [comment]
\o/ Coolio.

**Comment by molarmanful** [comment]
Could we touch up on the Ask Question/Propose Challenge buttons? They are really out of place (corners are too sharp, white background stands out way too much).

**Comment by addisoncrump** [comment]
I think you mean "Porpoise Challenge".

**Comment by vihanb** [comment]
@molarmanful they look fine to me but if you want, feel free to tweak it. I couldn't think of a good way to fit both buttons with better contrasting styles

**Comment by schas002** [comment]
Add support for Firefox. Many people use Firefox, but not Chrome, and I don't think that the user script will work in Firefox as it was originally made for Chrome (with Tampermonkey).

**Comment by RikerW** [comment]
Firefox support already exists. (To whoever was asking)

**Comment by vihanb** [comment]
"Please do not close until we graduate!" <- does that mean I should close this? :P

**Comment by ETHproductions** [comment]
@vihanb Look again at that sentence ;)

**Comment by RikerW** [comment]
Maybe a leaderboard that lists the most recently active 100? (out of ~700)

No byte counts, just a link and maybe the header.

**Comment by CrazyPython** [comment]
This looks too much like Code Review's theme...

**Comment by vihanb** [comment]
Are you using the old version? The new version looks nothing like CR

**Comment by CrazyPython** [comment]
I'm using the new version. ~~For example, square tag borders and the same font~~ Nevermind, it's just the fonts and the general layout

**Comment by vihanb** [comment]
So... like the rest of SE? >_>

**Comment by CrazyPython** [comment]
Do a side-by-side comparison with CR and another SE site and you'll see.

**Comment by Mego** [comment]
Feature request: get rid of this monstrosity and do feature requests like sane developers: one per issue.

**Comment by CrazyPython** [comment]
+1'ed

**Comment by schas002** [comment]
Opposition: get rid of trash in closed issues and do feature requests like we do now: in one thread.

**Comment by CrazyPython** [comment]
Closed issues are hidden and we don't have to have concurrent issues. Don't make me unleash the meta effect.

**Comment by RikerW** [comment]
> Feature request: get rid of this monstrosity and do feature requests like sane developers: one per issue.

Hammering this closed, for future reference: do what @Mego suggested.

**Comment by vihanb** [comment]
good idea, this will probably be a crash in gitgoat that I'll never fix, so it's better of closed

**Comment by RikerW** [comment]
lol
