### ISSUE TITLE
Support different kinds of bytes

### ISSUE THREAD

**Issue by molarmanful** [vihanb/PPCG-Design#11]
There's Piet's codels, there's LabVIEW Primitives, there's blytes (Minecraft). There's probably more. Those need support.

**Comment by ETHproductions** [comment]
Piet _might_ be possible, but I don't see how LabVIEW or Minecraft could be done. The image processing required for the latter two would be _waaaaaaaaaaaay_ more complex than I can design.

**Comment by vihanb** [comment]
Do you mean like for the leaderboard or for the inline byte counter?

**Comment by molarmanful** [comment]
Just the byte counter.

**Comment by vihanb** [comment]
I'm not sure whether processing Piet files is a _must_. Considering Piet is _very_ rarely used. I don't see too much of a benefit of adding parsing and reading Piet files, for the cost of load time, and speed

**Comment by molarmanful** [comment]
Hmm... how about TI-Basic? This might be a bit easier, perhaps.

**Comment by vihanb** [comment]
For reference, the TI-Basic token list is here: http://tibasicdev.wikidot.com/tokens

**Comment by vihanb** [comment]
I really doubt anyone's going to bother implementing this and it's highly unlikely that this will ever be used so I'm going to close this.
