### ISSUE TITLE
Add option to show the percentage an answer is longer than the shortest answer

### ISSUE THREAD

**Issue by somebody1234** [vihanb/PPCG-Design#110]

**Comment by RikerW** [comment]
that's actually a really good idea. a number of bytes also may be nice, i.e. `The shortest answer is 50% and 20 bytes shorter.`

**Comment by ETHproductions** [comment]
I agree with both ideas, though I vote for `The shortest answer is 20 bytes shorter (50%).` But where would this text be placed?

**Comment by somebody1234** [comment]
I'd say put it under the language name, because that's where your most visible bytecount is

**Comment by vihanb** [comment]
If we do add this, may I request that we have option to disable it

**Comment by somebody1234** [comment]
@vihanb well i did say "add option"

**Comment by vihanb** [comment]
Sorry, brain is not wokring today

**Comment by somebody1234** [comment]
I'd also like an option to count noncompeting answers.

**Comment by vihanb** [comment]
Idea: redo userscript in react so this is possible

**Comment by somebody1234** [comment]
We do not need to do that, just use jQuery like we always have

**Comment by vihanb** [comment]
@somebody1234 jQuery does very differnt from reawct
