### ISSUE TITLE
jQuery has left the userscript

### ISSUE THREAD

**Issue by ETHproductions** [vihanb/PPCG-Design#114]
The userscript has stopped working sometime in the last few days. I checked my browser console (in Firefox) and found that any time a PPCG page is loaded, this error message occurs:

    ReferenceError: $ is not defined

Unless I'm mistaken, we can no longer directly use jQuery... So what should we do?

**Comment by vihanb** [comment]
I believe there's a way to expose window to greasemonkey I did it for sandbox viewer

**Comment by ETHproductions** [comment]
OK, after reading [this post](http://stackoverflow.com/questions/24753908/trying-to-load-jquery-into-tampermonkey-script) I think what we need to do is

    // @require https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js

(That's the jQuery version that SE uses, we might choose to use a different one)

**Comment by ConorOBrien-Foxx** [comment]
Or, you know, you could try getting rid of jQuery. Just sayin'.

**Comment by RikerW** [comment]
but jquery is great and does all things

**Comment by ETHproductions** [comment]
@ConorOBrien-Foxx I'm sure that's possible, but we call jQuery 190 times throughout the userscript, many of which aren't for simple DOM manipulation tasks. It won't be anywhere close to easy, but if you'd like to try, go ahead... :P

**Comment by ConorOBrien-Foxx** [comment]
@ETHproductions  Hrmph. Oh well.

**Comment by vihanb** [comment]
Can we make a library that takes jquery code and converts it to sane JS

**Comment by somebody1234** [comment]
Yes definitely, but I want it to also turn insane JS into sane JS
