### ISSUE TITLE
Invisible text

### ISSUE THREAD

**Issue by kritixilithos** [vihanb/PPCG-Design#116]
In challenges, the grey boxes are not aligned at the bottom when the OP has edited their post. Also the post date and the amount of badges of the OP are invisible.

[![Not aligned](http://i.stack.imgur.com/W6gTf.png)](http://codegolf.stackexchange.com/questions/42017/print-a-negative-of-your-code)

**Comment by kritixilithos** [comment]
The same problem of invisible text exists in answers as well

**Comment by kritixilithos** [comment]
Also invisible avatars under the "edited" section

**Comment by kritixilithos** [comment]
And it happens on meta as well

**Comment by RikerW** [comment]
Fixed in [7cb36d1 ](https://github.com/vihanb/PPCG-Design/commit/7cb36d11347ff68d120898d649636efa01267433)
