### ISSUE TITLE
Usercard on questions is dark grey

### ISSUE THREAD

**Issue by RikerW** [vihanb/PPCG-Design#117]
<img width="387" alt="screen shot 2017-03-26 at 10 50 50 am" src="https://cloud.githubusercontent.com/assets/16050725/24333726/1b89952c-1212-11e7-8eb0-7c4541618a0b.png">

and:

<img width="468" alt="screen shot 2017-03-26 at 10 50 21 am" src="https://cloud.githubusercontent.com/assets/16050725/24333728/21429130-1212-11e7-803e-edb67f92d30c.png">

Looks like the CSS is causing it to have a dark grey background, making some text invis. [This is kinda a subset of this, but the grey background is what I'm referring to here.](https://github.com/vihanb/PPCG-Design/issues/116)

**Comment by vihanb** [comment]
Dupe of #116, perhaps caused by dark theme?

**Comment by RikerW** [comment]
Dark theme is off though... also: holy fuck just tested dark theme wth is that

**Comment by RikerW** [comment]
[fixed](https://github.com/vihanb/PPCG-Design/compare/6a5dad90b6c855e2f849836b43acb4036a0e467b...7cb36d11347ff68d120898d649636efa01267433)
