### ISSUE TITLE
Remove "Non-competing" filter from leaderboard

### ISSUE THREAD

**Issue by PeterShaggyNoble** [vihanb/PPCG-Design#127]
The leaderboard includes a [filter](/vihanb/PPCG-Design/blob/master/ppcg.user.js#L869) to remove any solutions that contain "non-competing" (and a few variations on that) in their header. However, now that we have [done away with "non-competing"](https://codegolf.meta.stackexchange.com/q/12877/58974), that filter can probably be removed.

**Comment by vihanb** [comment]
All of the older answers which are still marked 'non-competing' would still need to work with the leaderboard no?

**Comment by RikerW** [comment]
I already changed this, sorry, haven't had time to comment.   Aren't the older ones now valid though?

**Comment by vihanb** [comment]
@RikerW not for all. It would be valid to add a feature after a challenge posting and label it non-competing

**Comment by somebody1234** [comment]
@vihanb And that's perfectly valid, just heavily discouraged.
