### ISSUE TITLE
Upgoat and Downgoat icons no longer load

### ISSUE THREAD

**Issue by Mego** [vihanb/PPCG-Design#128]
It seems somebody1234 deleted their GitHub account, so the sprites are giving a 404. Hosting them in a different repository was an exceptionally poor idea.

**Comment by somebody1234** [comment]
No my account has been flagged for some reason >_> sorry will try to resolve this asap, I guess it *is* a pretty bad idea though. I will upload the sprites on here I guess. (Sorry was setting up a redirect site but I guess it looked like spam to GitHub)

**Comment by somebody1234** [comment]
Should be fixed now, can you please confirm

**Comment by Mego** [comment]
Fixed in 05d1e43
