### ISSUE TITLE
New design doesn't let me change settings

### ISSUE THREAD

**Issue by GolfingSuccess** [vihanb/PPCG-Design#129]
Recently, Stack Exchange underwent a design change, and the new design doesn't let me change the userscript's settings, since the settings icon doesn't appear.

**Comment by RikerW** [comment]
idea: another userscript to get to top bar back.

on a similar note, considering closing as "SE's fault for this fugly bar"

**Comment by vihanb** [comment]
fixed in ec5d782e7200ee148e8ce34750065bed018c1683
