### ISSUE TITLE
Gives user extra privileges

### ISSUE THREAD

**Issue by totallyhuman** [vihanb/PPCG-Design#130]
As you probably already know, only users with 750 reputation or above can see vote counts on posts on PPCG. However, if you have the userscript installed, whether you are a user with low reputation or not signed in at all, you can still see vote counts.

This isn't *really* a bug, more like an unintended feature. It's also one that Stack Exchange wouldn't be happy about. :P

**Comment by RikerW** [comment]
This is a known "bug" and it's existed for a while. There is even a chrome extension (not even a userscript) to show vote counts.  

Also, this is a completely intended feature.

**Comment by RikerW** [comment]
https://github.com/vihanb/PPCG-Design/commit/88740b76905411a1ad919fb895b3e410729d993b

**Comment by ETHproductions** [comment]
Yeah, it's literally specifically coded into the userscript. It would be near impossible to accidentally add this particular feature

**Comment by totallyhuman** [comment]
Fair, although I didn't look at the source (and I don't *really* know JS). The "feature" seems weird to me but that's up to you guys.

Thanks for responding!
