### ISSUE TITLE
Background consistency

### ISSUE THREAD

**Issue by molarmanful** [vihanb/PPCG-Design#15]
<img width="1440" alt="screen shot 2016-01-12 at 8 43 17 pm" src="https://cloud.githubusercontent.com/assets/7122029/12285272/24651936-b96d-11e5-9bb1-0e2ee3b8c474.PNG">
versus
<img width="1440" alt="screen shot 2016-01-12 at 8 43 43 pm" src="https://cloud.githubusercontent.com/assets/7122029/12285274/342d5b08-b96d-11e5-9869-6e092c8ed32a.PNG">
is inconsistent (which is really bugging me). We should probably fix this.

As a side note: perhaps the white main site background should be a light gray or similar to fill up that negative space. (after all, solid whites are not in line with our current color scheme...)

**Comment by vihanb** [comment]
In chat it was agreed to leave Meta as-is, which is why it wasn't changed.

**Comment by addisoncrump** [comment]
I agree with making it consistent and all the way down the page for the main site. It's weird if it's inconsistent, and it looks a bit empty when it's not filled down the page.
