### ISSUE TITLE
Some leaderboard entries still messed up

### ISSUE THREAD

**Issue by ETHproductions** [vihanb/PPCG-Design#16]
Take a look at the leaderboard on [this page](http://codegolf.stackexchange.com/q/69385/42545). For me, there are at least three buggy entries:
- 𝔼𝕊𝕄𝕚𝕟, 24 bytes - 24 _chars_, 42 _bytes_.
- **Lua**, 80 bytes - That should not be bold.
- Lang N/A, 162 bytes - The header text is "Python 162"; the language name should be "Python".

**Comment by vihanb** [comment]
:| everytime one leaderboard problem is fixed another one comes up... I'll try a fix when I have time

**Comment by molarmanful** [comment]
If you're using a regex, I think this should work most of the time: `/[\d.]+\s+(bl?ytes|codels)/g`. Probably could improved to handle other edge cases.

**Comment by vihanb** [comment]
We've got the byte counting down, the hard part is getting the language name.

**Comment by molarmanful** [comment]
So `/^(.+),?\s+[\d.]+\s+(bl?ytes|codels)/` doesn't work?

**Comment by vihanb** [comment]
[Here's a Regex101](https://regex101.com/r/vQ5jF0/1) of some cases.

**Comment by ETHproductions** [comment]
The fourth case had "bytse" instead of "bytes", that's why it wasn't working. I'll work on a better regex and more cases.

**Comment by ETHproductions** [comment]
This seems to work on most cases, as long as we remove <s></s> text (which we already do): https://regex101.com/r/vQ5jF0/2

**Comment by ETHproductions** [comment]
One more problem: the header "ESMin, 24 char (42 bytes)" (which isn't handled by the new regex either) is not really parse-able, since a challenge may be scoring in chars. Should we just ignore this possibility and always attempt to score in bytes?

**Comment by molarmanful** [comment]
That might be possible with a snippet that looks for "scoring is in bytes" or something like that in the question box.

**Comment by vihanb** [comment]
Hm, that'll be too unreliable and difficult imo. Perhaps just looking for duplicate scores and preferring bytes would work

**Comment by molarmanful** [comment]
Another problem: http://codegolf.stackexchange.com/questions/69834/geometry-is-so-fun

Edit is in the lead with 1 byte!

**Comment by ETHproductions** [comment]
LOL, apparently I saved edc65 146 bytes ;)

I'm not quite sure why that happened. Last time I worked on this, only the first h1/h2/h3/strong element was checked for the byte count. Perhaps something in that area has changed since then? I'll take a look.

**Comment by vihanb** [comment]
I might make a code-golf [test-battery] challenge based off this leaderboard problem
