### ISSUE TITLE
Leaderboard Fails on different separator

### ISSUE THREAD

**Issue by vihanb** [vihanb/PPCG-Design#2]
The current leaderboard is very strict on how the header must be formatted to avoid issues. But if the header uses a different separator, it fails:

``` md
# My_lang - 13 bytes
```

The header should also work for bad formatting caused by possibly new users:

``` md
**language 54 bytes**
```

**Comment by vihanb** [comment]
My proposed fix is to look for the first occurrence of `(\d+) (?:bytes?|chars?|characters?)` and if that doesn't exist, _then_ use the alternative RegEx

**Comment by ETHproductions** [comment]
We can do that. I'll push a fix to load the full leaderboard for questions with more than 100 answers, then see if I can fix this in the way you mentioned.

**Comment by ETHproductions** [comment]
This has been fixed in the latest commit. All formats are now (supposedly) supported. We'll see if any more problems come up...
