### ISSUE TITLE
Python Code Blocks Interpreted as ISO-8859-1

### ISSUE THREAD

**Issue by addisoncrump** [vihanb/PPCG-Design#21]
![screen shot 2016-01-24 at 9 14 37 pm](https://cloud.githubusercontent.com/assets/10711159/12538970/9ace8492-c2df-11e5-8361-e88c233ea53e.png)

This happens to all python answers in Safari 9.1.

**Comment by ETHproductions** [comment]
That's because the header matches the regex `/Pyth/`. This will be fixed momentarily.
