### ISSUE TITLE
><> is called Lang N/A in Leaderboard

### ISSUE THREAD

**Issue by addisoncrump** [vihanb/PPCG-Design#24]
![screen shot 2016-01-25 at 4 13 54 am](https://cloud.githubusercontent.com/assets/10711159/12542351/1a2163c4-c31a-11e5-8ed3-afdef6fc4800.png)

![screen shot 2016-01-25 at 4 13 20 am](https://cloud.githubusercontent.com/assets/10711159/12542339/05cebd90-c31a-11e5-8995-c3fc1690a4a9.png)

It may be caused by parenthesis, because there was also this in there:

![screen shot 2016-01-25 at 4 14 45 am](https://cloud.githubusercontent.com/assets/10711159/12542364/32b2eb06-c31a-11e5-8e82-3aa92a5ff6df.png)

**Comment by vihanb** [comment]
Do you have a link to the post?

**Comment by addisoncrump** [comment]
http://codegolf.stackexchange.com/q/13152/44713
