### ISSUE TITLE
Redesigned redesign

### ISSUE THREAD

**Issue by vihanb** [vihanb/PPCG-Design#25]
So I've redesigned a portion and now it looks better than ever imo. I've kept my changes in the `ppcg.alt.user.js`, if everyone likes it I'll move it to `ppcg.user.js`.

Gif of parallax:

![scroll](https://cloud.githubusercontent.com/assets/15314511/12570016/1666c8d6-c389-11e5-9e42-96da99b764df.gif)

**Updated** Screenshot:

<img width="1340" alt="screen shot 2016-01-25 at 5 29 00 pm" src="http://i.stack.imgur.com/O2970.png">

---

**Please tell me if you like this or if you don't**

**Comment by molarmanful** [comment]
By the way, not all of the colors (esp. the greens) have been adjusted to fit the new scheme.

**Comment by vihanb** [comment]
Whoops, updated

**Comment by molarmanful** [comment]
Also, Meta?

**Comment by vihanb** [comment]
eh, I'll do it but later when I have more time (by later I mean in about 15 minutes)

**Comment by vihanb** [comment]
@ETHproductions your opinion on this?

**Comment by addisoncrump** [comment]
This looks beautiful. +1

**Comment by ETHproductions** [comment]
I like it as well. The one problem I've noticed so far is that on question pages, the question title appears closer to the dark-green top-bar than it should. But perhaps this is just me.
