### ISSUE TITLE
Meta Redesign

### ISSUE THREAD

**Issue by vihanb** [vihanb/PPCG-Design#26]
I've redesign meta now also and I think it looks pretty damn good.

<img width="1278" alt="screen shot 2016-01-27 at 8 35 21 pm" src="https://cloud.githubusercontent.com/assets/15314511/12635206/b42682ac-c535-11e5-8b36-daa6215d8238.png">

Opinions?

**Comment by molarmanful** [comment]
Not bad not bad... I like it!

**Comment by addisoncrump** [comment]
+1, should have the background text as answers to [tag:metagolf] questions.
