### ISSUE TITLE
Propose Question fixes

### ISSUE THREAD

**Issue by addisoncrump** [vihanb/PPCG-Design#31]
Propose Question buttons should not be on Meta, and the `Questions Tags Users...` bar needs to move up a bit (it slips into the page on far zoom).

**Comment by vihanb** [comment]
Could a take a screenshot of your page? I've used a solution to center it which may not work well on older browsers

**Comment by addisoncrump** [comment]
![screen shot 2016-01-31 at 4 36 22 pm](https://cloud.githubusercontent.com/assets/10711159/12703344/d0ffae98-c838-11e5-962f-08387079395d.png)

**Comment by molarmanful** [comment]
Oh jeez that's screwed up...

**Comment by vihanb** [comment]
oh wow :\ I probably need to add some `-webkit` prefixes

**Comment by addisoncrump** [comment]
Latest update did not fix the problem:

![screen shot 2016-01-31 at 4 42 44 pm](https://cloud.githubusercontent.com/assets/10711159/12703383/b8743276-c839-11e5-9776-0b4809620111.png)

**Comment by vihanb** [comment]
I've pushed a fix, let me know if this doesn't fix it

**Comment by addisoncrump** [comment]
![screen shot 2016-01-31 at 4 46 12 pm](https://cloud.githubusercontent.com/assets/10711159/12703401/307d9942-c83a-11e5-95a4-a7bd8db28ad3.png)

Fixed it, but maybe shortening the background again? It feels a little awkward.

**Comment by vihanb** [comment]
Fixed in eb024c3ba9c140d461df68c53ffc5bdd12591b40

**Comment by vihanb** [comment]
Never mind, that didn't work :/

**Comment by vihanb** [comment]
Okay, fixed in: 0207a08e51b3fc21f84962e040986f79b7a529e9

**Comment by addisoncrump** [comment]
Perfect. :D
