### ISSUE TITLE
Question of the Day breaks on apostrophes

### ISSUE THREAD

**Issue by addisoncrump** [vihanb/PPCG-Design#32]
![screen shot 2016-01-31 at 12 21 58 pm](https://cloud.githubusercontent.com/assets/10711159/12702072/480e1c28-c815-11e5-9761-c6c992316de4.png)

All of the other questions in the list were displayed correctly, but the apostrophe, it did not like.

**Comment by vihanb** [comment]
This can be fixed with a replace... I'll be on it

**Comment by addisoncrump** [comment]
This is still an issue for me.

**Comment by vihanb** [comment]
hm :\ then I'm not sure on how to fix it. I'm also not sure on exactly how the widget is constructed. Perhaps @JJ-Atkinson could help?

**Comment by JJ-Atkinson** [comment]
What do you need to know?

**Comment by vihanb** [comment]
Where (which line/function) is the apostrophe problem located?

**Comment by JJ-Atkinson** [comment]
Your commit fixed it, but it is where cookies are set, and that is why @VTCAKAVSMoACE  still sees the problem.

**Comment by JJ-Atkinson** [comment]
I just realized that your commit fixed it, but @VTCAKAVSMoACE  still sees the problem because your code doesn't change the cookie if it is already set.

**Comment by addisoncrump** [comment]
That fixed it. Coolio.

**Comment by JJ-Atkinson** [comment]
![image](https://cloud.githubusercontent.com/assets/16200906/12785060/22df9d54-ca50-11e5-87c3-ccd84f72ef64.PNG)

Still an issue. The cookie is not properly set.

![image](https://cloud.githubusercontent.com/assets/16200906/12785047/18644244-ca50-11e5-88cb-7dd8a0ba1921.PNG)

**Comment by addisoncrump** [comment]
Was just about to put this up.

**Comment by addisoncrump** [comment]
Any progress?

**Comment by JJ-Atkinson** [comment]
I think I fixed it in PR #95. Hope it works! Let me know if it breaks again :)

**Comment by RikerW** [comment]
fixed for me ^ closing
