### ISSUE TITLE
Duplicate Byte count

### ISSUE THREAD

**Issue by vihanb** [vihanb/PPCG-Design#33]
<img width="698" alt="screen shot 2016-01-31 at 4 49 44 pm" src="https://cloud.githubusercontent.com/assets/15314511/12706463/b1dde5fa-c83a-11e5-906a-6af4f6b5d7d5.png">

[Seen on this post](http://meta.codegolf.stackexchange.com/a/5639/40695)

**Comment by addisoncrump** [comment]
This is because one-boxing for code blocks is interpreted as either 4 spaces _or_ as `<pre><code></code></pre>`. This uses both - it's not a bug, it's something that we can't really handle.

**Comment by vihanb** [comment]
wrong issue :|

**Comment by RikerW** [comment]
rofl
