### ISSUE TITLE
Fonts in chat room

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [vihanb/PPCG-Design#38]
The header font broke: http://i.imgur.com/oCnzm7L.png

Also, the font is considerably smaller than the default; can you increase the size a bit?

Thanks! (On firefox (latest) and windows 8)

**Comment by RikerW** [comment]
Will work on it.

**Comment by RikerW** [comment]
BTW, it is also sorta broken for italics and bold other places to.

**Comment by RikerW** [comment]
Aaanndd it is my job now. <s>\o/</s> :P

**Comment by RikerW** [comment]
Doesn't work for me, and I am on the latest version.

**Comment by RikerW** [comment]
<img width="392" alt="screen shot 2016-02-07 at 8 29 54 am" src="https://cloud.githubusercontent.com/assets/16050725/12873554/fecb42ce-cd74-11e5-85e4-d7e87b17843f.png">
See?

**Comment by vihanb** [comment]
D: Whaaaat

**Comment by vihanb** [comment]
maybe it's the jquery

**Comment by RikerW** [comment]
Must be.

**Comment by vihanb** [comment]
fixed the jquery

**Comment by RikerW** [comment]
YAY! Works now.

**Comment by vihanb** [comment]
:D jquery is the best
