### ISSUE TITLE
Style out the buttons

### ISSUE THREAD

**Issue by molarmanful** [vihanb/PPCG-Design#5]
The current buttons (orange color) don't fit in well with the style. I was thinking a flat-style button, but here's the place to plan out how we'll approach buttons.

**Comment by vihanb** [comment]
I was thinking of using the browser default buttons. This looks _kinda_ fine on Safari, not sure about other browsers

**Comment by molarmanful** [comment]
How's this for a button?
<img width="145" alt="screen shot 2016-01-10 at 9 20 04 am" src="https://cloud.githubusercontent.com/assets/7122029/12222797/68845940-b77b-11e5-9e3b-0249a498676e.PNG">

**Comment by vihanb** [comment]
Sweet, that looks good, I'll close this then and merge your pull request
