### ISSUE TITLE
Meta answering remove loopholes

### ISSUE THREAD

**Issue by RikerW** [vihanb/PPCG-Design#58]
When writing a sandbox post or other meta answer, you don't really need the loophole suggestion.  Maybe a special case for the sandbox and turned off for the rest of meta?

**Comment by ETHproductions** [comment]
Fixed in commit 847d97484da3315ac767afcce153ff3bcefb55c9.

**Comment by RikerW** [comment]
Fixed more in commit [48b0fcb](https://github.com/vihanb/PPCG-Design/commit/48b0fcb3c8ced25f79c9a1408123f5aa85150fdc).  Yay! : P
