### ISSUE TITLE
Favicon not changing

### ISSUE THREAD

**Issue by molarmanful** [vihanb/PPCG-Design#6]
For some reason, the favicon is still the zipper logo. (Using latest Chrome...)

**Comment by ETHproductions** [comment]
On latest Firefox, it's the standard blue/white "PCG" speech bubble.

**Comment by molarmanful** [comment]
Actually, this seems to work fine for me after deleting a previous userscript that I was using. However, there still appears to be a bug, so I'll leave this issue open.
