### ISSUE TITLE
Clicked badge text is darker than all other badges

### ISSUE THREAD

**Issue by Mego** [vihanb/PPCG-Design#60]
<img src="http://i.imgur.com/9SYJUWC.png"></img>

No, I'm not just trying to show off my badges here :P

**Comment by vihanb** [comment]
try updating? looks fine for me

**Comment by Mego** [comment]
I've discovered the cause: the text is darker (and unreadable) on badges that have been clicked (like blue/purple links elsewhere)

**Comment by vihanb** [comment]
`a.badge { color: white !important }` <- that CSS should fix it, I'll put it in later as I'm to lazy do it right now

**Comment by vihanb** [comment]
I think I fixed this
