### ISSUE TITLE
"Before you post, take some time to..." appears on meta as well as the main site

### ISSUE THREAD

**Issue by catb0t** [vihanb/PPCG-Design#62]
Example: http://meta.codegolf.stackexchange.com/a/8557/46231

Not a huge thing, but perhaps it doesn't make much sense for a blurb about reading the forbidden loopholes to appear on _meta_.

**Comment by ETHproductions** [comment]
This also appears under "About Me" on the edit profile page, I noticed while editing the ETHbot account.

**Comment by catb0t** [comment]
What I was experiencing was fixed, I just needed to click "Update" in Tampermonkey. You should open a new issue.

**Comment by RikerW** [comment]
Okay, thanks, I though I fixed that. ^_^
