### ISSUE TITLE
Review page header is broken and meta header everywhere

### ISSUE THREAD

**Issue by RikerW** [vihanb/PPCG-Design#63]

**Comment by RikerW** [comment]
The review page header is borked.

**Comment by RikerW** [comment]
http://i.imgur.com/XiYfNy2.png

**Comment by RikerW** [comment]
http://i.imgur.com/fSZ4CGy.png Meta is broken too.

**Comment by huesatlum** [comment]
It was randomly trying to add an `s` variable to the CSS that didn't exist. I've removed it, as I'm not sure what it was supposed to be doing
