### ISSUE TITLE
Links are black

### ISSUE THREAD

**Issue by vihanb** [vihanb/PPCG-Design#64]
ever since we graduated the links are black. They should be green.

**Comment by The-Quill** [comment]
Can you screenshot exactly which links you're talking about?

**Comment by vihanb** [comment]
not all links but in some places:

On profile page:
<img width="319" alt="screen shot 2016-02-26 at 9 48 44 pm" src="https://cloud.githubusercontent.com/assets/15314511/13371092/c37d7d5a-dcd2-11e5-9698-c9baf470e905.png">

In footer:
<img width="172" alt="screen shot 2016-02-26 at 9 49 11 pm" src="https://cloud.githubusercontent.com/assets/15314511/13371099/d1a00bdc-dcd2-11e5-8baa-4c08036e5cb0.png">

**Comment by The-Quill** [comment]
What flavour of green should they be?

**Comment by RikerW** [comment]
There are actually a lot of dark green ones in places that need to be fixed.  The already clicked ones turn dark and that makes them hard to see.

**Comment by somebody1234** [comment]
@vihanb You should probably change the color now. (Or at least say what to change it to)

**Comment by vihanb** [comment]
solution is to complain to SE to ungraduate us so this userscript works

**Comment by RikerW** [comment]
@vihanb thanks for the helpful response. Downgoat is the best goat +1

**Comment by vihanb** [comment]
@RikerW ಠ_ಠ

**Comment by vihanb** [comment]
oh hey i can edit comments

**Comment by RikerW** [comment]
Hey, the truth hurts... No seriously though, the emails notifications are annoying. If you don't fix it, transfer ownership of this repo to me.

**Comment by RikerW** [comment]
You open it and state the reason, you fix it.

**Comment by vihanb** [comment]
that logic is flawed

**Comment by vihanb** [comment]
I don't know what's causing it so I can't exactly fix it

**Comment by vihanb** [comment]
I've tried to find out but I don't feel like spending 3 hours debugging a tiny color bug

**Comment by RikerW** [comment]
The default colors are black, hard to read on the dark green bg. Solution: Write a function to add the `.lightgreen` class to all of the elements in the bottom footer. Then set that class to text color #78ee74.

**Comment by RikerW** [comment]
Graduation removed a couple styling things, and added it's own.

**Comment by RikerW** [comment]
^ was a dupe.

**Comment by vihanb** [comment]
I've implemented a partial fix. Should fix the footer

**Comment by RikerW** [comment]
hell no, that looks freaking awful.

**Comment by vihanb** [comment]
that wasn't my fix. It was someone else....

**Comment by vihanb** [comment]
now my fix should come into effect... (though its not finished)
