### ISSUE TITLE
Lighter background is squished

### ISSUE THREAD

**Issue by ETHproductions** [vihanb/PPCG-Design#66]
I noticed today after accidentally switching to the light background on main that the hexagonal background is squished to about 10% vertical scale. Also, the "lighter background" option doesn't seem to do anything on meta.

**Comment by vihanb** [comment]
under settings, have you checked "Lighter Background" accidentally?

**Comment by ETHproductions** [comment]
Whoops, that box had been checked, and `localStorage['main.BACKGROUND_LIGHT']` was `"true"`. Thanks! But why is the background squashed vertically?

**Comment by vihanb** [comment]
the background images are different sizes and the `background-size` (which scales the background down so it doesn't appear huge) isn't changed when light background is set

**Comment by RikerW** [comment]
I got this, but I need a day or two.
