### ISSUE TITLE
Can't tell the difference between starred pinned chat messages and just starred

### ISSUE THREAD

**Issue by huesatlum** [vihanb/PPCG-Design#67]
On the starboard, a pinned message usually has a black outline (and gold fill if you've starred it), but with the userscript it looks the same as any other starred message (i.e. no black outline).
I'm not even sure why we need new chat stars in the first place. They look the same to me.

**Comment by vihanb** [comment]
For me, the old stars look very low-res (I have a high-dpi display). I'll change it back if no one else uses a HI DPI display but in the meanwhile I'll try to fix it

**Comment by somebody1234** [comment]
Doesn't look like it's happening anymore to me
