### ISSUE TITLE
A sandbox automated directory

### ISSUE THREAD

**Issue by RikerW** [vihanb/PPCG-Design#72]
Maybe a leaderboard that lists the most recently active 100?  (out of ~700)  

No byte counts, just a link and maybe the header.

**Comment by molarmanful** [comment]
You should put this in the feature-request issue thread instead. (Just saying...)

**Comment by RikerW** [comment]
@molarmanful oops, done.

**Comment by addisoncrump** [comment]
Closing, as this exists in the feature request thread now.
