### ISSUE TITLE
Footer is unreadable

### ISSUE THREAD

**Issue by Mego** [vihanb/PPCG-Design#77]
<img src="http://img.prntscr.com/img?url=http://i.imgur.com/sBJ1901.png">

**Comment by RikerW** [comment]
> _> you had to point that out... I investigated a while ago, couldn't figure out how to fix easily. Let Downgoat do it.

**Comment by vihanb** [comment]
![I could fix it but I don't feel like it](https://camo.githubusercontent.com/d58c5fc5c80f05d4d4d7ada765b4786a9b77c812/687474703a2f2f692e696d67666c69702e636f6d2f31306f3034322e6a7067)

**Comment by vihanb** [comment]
give me the color to change it to and ill fix it

**Comment by RikerW** [comment]
Pink?

**Comment by RikerW** [comment]
@vihanb #78ee74

**Comment by vihanb** [comment]
okay, will attempt to fix

**Comment by RikerW** [comment]
This is the same as [this](https://github.com/vihanb/PPCG-Design/issues/64) issue, closing. Progress will be recorded there.

**Comment by RikerW** [comment]
Same cause at least.
