### ISSUE TITLE
Before editing your profile, make sure you look through the loopholes.

### ISSUE THREAD

**Issue by DJMcMayhem** [vihanb/PPCG-Design#78]
Today, I edited my profile settings, when I noticed something strange in the PPCG design.

![edit](https://cloud.githubusercontent.com/assets/12721641/15614345/7e666bfe-23f5-11e6-8192-df1a55176b7c.png)

(Lovingly filled in with red freehand circles)

I'm not exactly sure what loopholes there are for my account. Maybe we need to make a meta post informing people of the account loopholes they should avoid? For example, inventing a profile while the challenge is still in the sandbox, using builtins that defeat the purpose of your profile, or compiling your profile too literally. These are all terrible things we should tell people to avoid in their profile.

**Comment by RikerW** [comment]
minus won not bright red

**Comment by RikerW** [comment]
I will start on that meta post as soon and/or try to fix that.

**Comment by vihanb** [comment]
ಠ_ಠ for dark red circles

**Comment by RikerW** [comment]
@vihanb ninja'ed:

> minus won not bright red

**Comment by DJMcMayhem** [comment]
![edit2](https://cloud.githubusercontent.com/assets/12721641/15621046/5d382cee-241b-11e6-9b2d-6b9e3c65d119.png)

**Comment by RikerW** [comment]
D: PINK IS HORROR

Seriously, can you see colors like a normal human being please? Try RGB(255,0,0).

**Comment by DJMcMayhem** [comment]
![pink](https://cloud.githubusercontent.com/assets/12721641/15621458/5452a46c-241e-11e6-8259-3f4bcdbf87b2.png)

**Comment by RikerW** [comment]
JUST USE 255,0,0

**Comment by vihanb** [comment]
^

**Comment by vihanb** [comment]
Nice up/downgoats btw

**Comment by RikerW** [comment]
Congrats github, I got an email about this today.
