### ISSUE TITLE
Byte counter lies

### ISSUE THREAD

**Issue by Mego** [vihanb/PPCG-Design#79]
![image](https://cloud.githubusercontent.com/assets/853264/16442358/9d902c20-3d97-11e6-96e5-c62ef4969689.png)

Though Pyth uses ISO-8859-1 by default, not all of the characters present in the code are in that encoding. Thus, the encoding falls back to UTF-8, and the byte count is incorrect.

[Referenced answer](http://codegolf.stackexchange.com/a/83908/45941)

**Comment by ETHproductions** [comment]
Should be fixed now.
