### ISSUE TITLE
Leaderboard show the same rank for same length answer

### ISSUE THREAD

**Issue by ghost** [vihanb/PPCG-Design#80]
![2016-07-12 2](https://cloud.githubusercontent.com/assets/12471641/16776555/2a644a22-4866-11e6-8797-873c090aed86.png)
Everything is in the title ;_;

**Comment by schas002** [comment]
It's ~~probably~~ **_obviously**_ by design.

**Comment by vihanb** [comment]
That's supposed to happen?
