### ISSUE TITLE
Before posting a challenge, please read the standard loopholes!: Follow-up

### ISSUE THREAD

**Issue by GolfingSuccess** [vihanb/PPCG-Design#83]
You should include a link to the sandbox.

**Comment by somebody1234** [comment]
I don't think that's needed, we already put a link to the sandbox _right next to_ a link to post a question.

**Comment by GolfingSuccess** [comment]
@somebody1234 Yeah, but someone might not notice that 'Challenge Proposing' goes before 'Challenge Posting'.

**Comment by somebody1234** [comment]
Maybe we should remove that and add a link to autopost on sandbox questions you own?

**Comment by GolfingSuccess** [comment]
@somebody1234 I don't know what you mean here, but a notice would be good, i.e. "Be sure to post this challenge to the sandbox first, if you haven't alerady done so." Also, the link would be useful, i.e. take you to a ready question page, just to make slight modifications and then post.

**Comment by RikerW** [comment]
@erikkonstas  he means a button that when you click it, opens you to the "New Question" page with the contents of your sandboxed post already filled in. So all you have to do is click "post".

**Comment by vihanb** [comment]
In that case use PPCG sandbox viewer?

**Comment by GolfingSuccess** [comment]
@vihanb &lt;insert very offensive message here ;_;&gt;

**Comment by GolfingSuccess** [comment]
@RikerW What about the tags? Will they be alerady in or what? I need to get the tags in. Also, the title must be provided.

**Comment by somebody1234** [comment]
@erikkonstas yes

**Comment by vihanb** [comment]
@erikkonstas do you use firefox? That's probably it then

**Comment by GolfingSuccess** [comment]
@vihanb No, I use Chrome (not Chromium).
