### ISSUE TITLE
Multiple numbers in header trips leaderboard

### ISSUE THREAD

**Issue by ETHproductions** [vihanb/PPCG-Design#88]
For example, this header:
### Java 8 7, <s>512</s> 490 + 19(import) bytes

is parsed as 19 bytes. Not sure what should be done about this.

[Reference](http://codegolf.stackexchange.com/a/92716/42545)

**Comment by addisoncrump** [comment]
Checks for the `+` sign? Edits made to answers to have `= <num>` at the end to show their real values last?
