### ISSUE TITLE
.

### ISSUE THREAD

**Issue by betseg** [vihanb/PPCG-Design#90]
.

**Comment by rjhunjhunwala** [comment]
Why is this not a legitimate feature request considered good?

**Comment by RikerW** [comment]
It's not that it's a bad request. I responded in chat to him, and told him it's a dumb idea. I would edit it back out if downgoat added it. 

Nothing about it being bad, closing just means the answer is no.

**Comment by RikerW** [comment]
@betseg no, leave the title as is. That way people know why it was closed.

**Comment by rjhunjhunwala** [comment]
@RikerW Honestly I thought this was just a satirical feature request. I'll be  honest I don't think this should be at all part of the official release. (although people can fork this and (somewhat trivially) add it.

**Comment by RikerW** [comment]
@rjhunjhunwala yeah, exactly. (satirical ones still get closed though) Also, for further discussion ping me in chat. Everybody watching this repo get an email for each comment here.

**Comment by rjhunjhunwala** [comment]
I don't disagree it should get closed.
