### ISSUE TITLE
Challange of the day is defferent on the meta site

### ISSUE THREAD

**Issue by JJ-Atkinson** [vihanb/PPCG-Design#99]
The QOD widget shows different questions on the meta site than are shown on the main site. This is because local storage isn't able to cross domains. I don't know if this is a big deal to anyone, but I figured I should open an issue.

**Comment by RikerW** [comment]
IMO disabling the QOD widget for meta is a fine solution to this problem, though that's just me.

**Comment by JJ-Atkinson** [comment]
I just realized that this extends to all localstorage stuff -- including all the settings. So when you change the settings on the main site you need to change them again on the meta site...

**Comment by ETHproductions** [comment]
Fixed by disabling QOD on meta in ade68b0.
